### PR TITLE
Dheeraj 22 scse1012360

### PR DESCRIPTION
**Pull request by WHitE-TITaN**

### CODE REVIEW

**Comment by aniisunny** [comment]
Please correct the folder structure delete unwanted file from pull request before merging this 

.vs folder does not need
.json file also not need

**Review by WHitE-TITaN — COMMENTED** [review]
sir, 
can you please review the directory now.

**Comment by aniisunny** [comment]
kudos to you 

you write the clean code 

good quality of code love it

**Comment by WHitE-TITaN** [comment]
> kudos to you
> 
> you write the clean code
> 
> good quality of code love it

### ThankYou Sir,
This will really help me to stay motivated and move forward.

**Pull request merged**
